### ISSUE TITLE
Headings out of place on dstar and other modes

### ISSUE THREAD

**Issue by jrhutchings** [rohithzmoi/Droidstar-DMR#3]
Last heard overlays user text on main display. Headings seem to overlay and not line up properly. On Dmr country on first last heard overlays first line of second contact

**Comment by 777Naity** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by jrhutchings** [comment]
Can I get a request to get the iPhone version. How do I do that.

**Comment by jrhutchings** [comment]
Just tried the download link says it contains a virus. I am sure it does not but could not down load it. Can you create a new downloadable apk.

**Comment by rohithzmoi** [comment]
> Last heard overlays user text on main display. Headings seem to overlay and not line up properly. On Dmr country on first last heard overlays first line of second contact

Thank you, this will be fixed in the next update(s)

For iPhone invite, please mail me at vu3lvo@proton.me

The APK link on the Readme file - https://inz.to/droidstar-vu3lvo works very well. 
If using chrome/safari, please select "Allow Download" and it should work.

**Comment by rohithzmoi** [comment]
UI Overlaps and issue is fixed. Update released.
